<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseWPF>true</UseWPF>
    </PropertyGroup>

    <ItemGroup>
        <Folder Include="Assets\Sprites\"/>
        <Folder Include="exceptions\"/>
    </ItemGroup>

    <ItemGroup>
        <None Remove="Assets\Sprites\DogFront2.png"/>
    </ItemGroup>

    <ItemGroup>
        <None Remove="Assets\Sprites\Pets\Mouse.png"/>
        <Resource Include="Assets\Sprites\Pets\Mouse.png"/>
        <None Remove="Assets\Sprites\Food\apple.png"/>
        <Resource Include="Assets\Sprites\Food\apple.png"/>
        <None Remove="Assets\Sprites\Food\WaterBottle.png"/>
        <Resource Include="Assets\Sprites\Food\WaterBottle.png"/>
        <None Remove="Assets\Sprites\Games\FoodCollector.png"/>
        <Resource Include="Assets\Sprites\Games\FoodCollector.png"/>
        <None Remove="Assets\Sprites\Games\PetJump.png"/>
        <Resource Include="Assets\Sprites\Games\PetJump.png"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="ColorHelper" Version="1.8.1"/>
        <PackageReference Include="CommunityToolkit.Diagnostics" Version="8.4.0"/>
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0"/>
        <PackageReference Include="ValueConverters" Version="3.1.22" />
    </ItemGroup>

    <ItemGroup>
        <Page Update="UI\GameWindows\FoodCollectorMiniGameWindow.xaml">
            <Generator>MSBuild:Compile</Generator>
            <XamlRuntime>Wpf</XamlRuntime>
            <SubType>Designer</SubType>
        </Page>
        <Page Update="UI\GameWindows\PetJumpMiniGameWindow.xaml">
            <Generator>MSBuild:Compile</Generator>
            <XamlRuntime>Wpf</XamlRuntime>
            <SubType>Designer</SubType>
        </Page>
        <Page Update="UI\ResourceDictionaries\MiniGameResources.xaml">
            <Generator>MSBuild:Compile</Generator>
            <XamlRuntime>Wpf</XamlRuntime>
            <SubType>Designer</SubType>
        </Page>
        <Page Update="UI\GameWindows\customControls\UI\CollectablesDisplay.xaml">
            <Generator>MSBuild:Compile</Generator>
            <XamlRuntime>Wpf</XamlRuntime>
            <SubType>Designer</SubType>
        </Page>
        <Page Update="UI\GameWindows\customControls\UI\TimerDisplay.xaml">
            <Generator>MSBuild:Compile</Generator>
            <XamlRuntime>Wpf</XamlRuntime>
            <SubType>Designer</SubType>
        </Page>
        <Page Update="UI\GameWindows\customControls\UI\PauseMenu.xaml">
            <Generator>MSBuild:Compile</Generator>
            <XamlRuntime>Wpf</XamlRuntime>
            <SubType>Designer</SubType>
        </Page>
    </ItemGroup>

</Project>
